name = "indo" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "indo.gretongersjateng.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.indo.gretongersjateng.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.indo.gretongersjateng.my.id
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.indo.gretongersjateng.my.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeenobile.com.indo.gretongersjateng.my.id
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "2ab23338-0613-474b-b33d-47c72f4f3194"
