name = "sg1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "sg1.yasnaya.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.yasnaya.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "1b36e5c2-4512-4332-a1c0-6615b044dace"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
