name = "Alipastore" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
PROXYIP = "211.230.110.231:50008"
UUID = "dca600ef-f7ed-4aa7-9c72-3c2a320eba64"
