name = "server-sg" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.adit2.web.id"
custom_domain = true
[[routes]]
pattern = "bayar.ruangguru.com.sg1.adit2.web.id"
custom_domain = true
[[routes]]
pattern = "career.ruangguru.com.sg1.adit2.web.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "76a374d2-eeb1-4dcc-a188-8b8c3432f373"
