name = "SG" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true
[[routes]]
pattern = "sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "api.joox.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "account.pmang.game.naver.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "we5.web.whatsapp.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "access.iflix.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "edge-ig-mqtt-p4-shv-01-cgk1.facebook.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg.uingtunnel.me"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg.uingtunnel.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "262df6cd-9de8-4d33-a78d-1c5987ad8395"
