name = "sgdo"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "sg1.apilyolanda.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.apilyolanda.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.apilyolanda.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "00758f40-a73f-48be-92c3-294aa37b293a"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
